# Generated by Django 5.1.4 on 2025-01-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('religion', models.TextField()),
                ('race_color_national_origin', models.TextField()),
                ('sex_gender_preferences', models.TextField()),
                ('disability', models.TextField()),
                ('familial_status', models.TextField()),
                ('source_of_income', models.TextField()),
                ('arrest_conviction_records', models.TextField()),
                ('eviction_history', models.TextField()),
                ('credit_score_employment', models.TextField()),
                ('coded_language', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='scrappeddata',
            name='issue',
            field=models.BooleanField(default=False),
        ),
    ]
