# Generated by Django 5.1.4 on 2025-02-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_newopenaianalysis_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newopenaianalysis',
            name='category',
        ),
        migrations.AddField(
            model_name='newopenaianalysis',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newopenaianalysis',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
