# Generated by Django 5.1.4 on 2025-02-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_newopenaianalysis_isdiscriminatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
