# Generated by Django 5.1.4 on 2025-01-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_scrappeddata_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrappeddata',
            old_name='delete',
            new_name='deleted',
        ),
    ]
