# Generated by Django 5.1.4 on 2025-01-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_delete_scrappeddata_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaianalysis',
            name='discriminatory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
