# Generated by Django 5.1.4 on 2025-02-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_openaianalysis_discriminatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOpenAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('comments', models.TextField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
