# Generated by Django 5.1.4 on 2025-02-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_newopenaianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='newopenaianalysis',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
