# Generated by Django 5.1.4 on 2025-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_newopenaianalysis_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newopenaianalysis',
            name='isDiscriminatory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newopenaianalysis',
            name='flagged',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
